# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0002_auto_20170412_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[(0, 'general meeting'), (1, 'fundraiser'), (2, 'event'), (3, 'other')], max_length=2),
        ),
        migrations.AlterField(
            model_name='repeatingevent',
            name='day_of_week',
            field=models.CharField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')], max_length=2),
        ),
        migrations.AlterField(
            model_name='repeatingevent',
            name='frequency',
            field=models.CharField(choices=[(0, 'daily'), (1, 'weekly'), (2, 'monthly'), (3, 'yearly')], max_length=2),
        ),
    ]
