# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0004_auto_20170412_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('general meeting', 'general meeting'), ('fundraiser', 'fundraiser'), ('event', 'event'), ('other', 'other')], max_length=50),
        ),
    ]
