# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0005_auto_20170412_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('General meeting', 'general meeting'), ('Fundraiser', 'fundraiser'), ('Event', 'event'), ('Other', 'other')], max_length=50),
        ),
    ]
