# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0008_auto_20170417_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('General meeting', 'General Meeting'), ('Fundraiser', 'Fundraiser'), ('Event', 'Event'), ('Other', 'Other')], max_length=50),
        ),
    ]
