# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0010_auto_20170418_0200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='organization_name',
        ),
        migrations.AlterField(
            model_name='repeatingevent',
            name='day_of_week',
            field=models.CharField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=200),
        ),
        migrations.AlterField(
            model_name='repeatingevent',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=200),
        ),
    ]
