# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 02:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0012_organization_organization_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarevent',
            name='calendar',
        ),
    ]
