# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 03:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0013_remove_calendarevent_calendar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repeatingevent',
            name='event_id',
        ),
        migrations.AddField(
            model_name='event',
            name='day_of_week',
            field=models.CharField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('None', 'None')], default='', max_length=200),
        ),
        migrations.AddField(
            model_name='event',
            name='end_repeat',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 20, 3, 18, 28, 592203, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='event',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('none', 'None')], default='', max_length=200),
        ),
        migrations.DeleteModel(
            name='RepeatingEvent',
        ),
    ]
