# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 04:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0023_event_end_repeat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Calendar',
        ),
    ]
