# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0028_delete_calendar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_repeat',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
